branch-defaults:
  default:
    environment: Udagram-be-env
environment-defaults:
  Udagram-be-env:
    branch: null
    repository: null
global:
  application_name: udagram-be
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: null
  workspace_type: Application
deploy:
  artifact: www/Archive.zip
