version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.7.0
  aws-cli: circleci/aws-cli@2.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
  # different jobs are calles later in the workflows sections

jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      # install yarn
      - run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV
      # install dependencies in both apps
      - run:
          name: Front-End Install
          command: |
            yarn frontend:install
      - run:
          name: Back-End Install
          command: |
            yarn backend:install
      - run:
          name: Front-End Build
          command: |
            yarn frontend:build
      - run:
          name: Back-End Build
          command: |
            yarn backend:build
      - run:
          name: Front-End Build
          command: |
            yarn frontend:build
      - run:
          name: Back-End Deploy
          command: |
            yarn backend:deploy
      - run:
          name: Backend set ENV
          command: |
            yarn backend:SETENV
      - run:
          name: Front-End Deploy
          command: |
            yarn frontend:deploy
